### ISSUE TITLE
Load the data model from XML files

### ISSUE THREAD

**Issue by unforbidable** [unforbidable/patcher#34]
Once loaded the complete data model will be represented as a tree of objects. There objects will be used to generate the class files for records and subrecords, but also enums, function index, and so on. The model tree will also be used to by the GUI and the Rule Engine. Reference manual pages will be also generated based on the model tree (i.e. instead of System.Reflection)

- [x] Records
- [x] Fields
- [x] Field Groups
- [x] Structures
- [x] Enumerations
- [x] Functions

**Comment by unforbidable** [comment]
Models files get loaded shortly after launch, with fairly detailed error reporting. Program option `--modelonly` can be used to force patcher exit once the model has been loaded.

**Comment by Desymoo** [comment]
I'm just putting this here for organization :)
**Definition of Record Structure Elements:**

Member types
Built in member types are: byte, sbyte, short, ushort, int, uint, float and string (including variations of string below).
These types can be also used as arrays with fixed length, e.g uint[4] or variable length e.g. byte[].
Arrays of variable length are used to load content of the whole field.
Enums can be used as member types.

Enums
Enums consist of enum members and each member must be the same underlying type.
Permitted enum types are as follows:  byte, sbyte, short, ushort, int, uint
Enums are always defined in separate files and can be used as member types.

Structures
Structures are made from members. Each members needs a name and type.
Structures may have a name. Structures without a name are called anonymous and these will not be generated.
Properties of anonymous structures will be geenerated in the parent scope (e.g. record or field group)
Structures can be defined in separate files for reusability or inline where they are needed.

Fields
Fields directly define the content of form records. Fields can be represented by a member (of any built in type or enums), a structure or a field group.
Fields have a key (eg. EDID), with the exeption of fields represented by a field group (in this case the keys of the child fields are used).
Fields can may be defined in separate files and included anywhere to avoid redundancy. When a field is included, it is possible (and other required)
to provide key and name.
Fields can be used a list.
Fields can be declared as virtual in which case there is no underlying data and only a property is generated.
Fields can be declared as hidden in which case no property is generated for them.
Properties of virtual fields can access one or more hidden fields (via so called adapters).

Field Groups
Field groups are sort of like structures, but they contain fields (basically, memebers with keys).
Field groups will be generated sort of like structures.

Records
Records consist of fields. 
Every records has a unique form type (e.g. KYWD) which is inferred from the name of the file in which they are defined.
Records also have a user friendly name (e.g. Keyword).

**Comment by unforbidable** [comment]
Thank you. Good idea! Eventually this should go to the wiki, once you translate it to "human". (:

**Comment by unforbidable** [comment]
Forgot to load functions!

**Comment by unforbidable** [comment]
Model object relations in the data model tree:
![data model tree](https://user-images.githubusercontent.com/14938119/37298796-ab26953a-2621-11e8-93e5-5afdb3703aa7.png)
