### ISSUE TITLE
Finish writing the new XML files for all currently supported form types

### ISSUE THREAD

**Issue by Desymoo** [unforbidable/patcher#43]
Ideally, for the releases all currently supported form types should still be supported with the new XML data model. Form types to support:
- [x] ALCH
- [x] AMMO
- [x] ARMO
- [x] COBJ
- [x] FLST
- [x] GLOB
- [x] GMST
- [x] IMAD
- [x] IMGS
- [x] KYWD
- [x] PROJ
- [x] WEAP
- [x] WTHR

And the list of unfinished fields that will need their own XML file:
- [x] virtual-machine (scripting data)
- [x] body-template (for armor-related records)
- [x] destructible (destruction data)
- [x] actor-value

Also the function index (`functions/functions.xml`) including function parameters should be completed:
- [x] Functions

**Comment by unforbidable** [comment]
I had a look at the list of form types currently supported by patcher. Out of these, so far we have got: ALCH, AMMO, COBJ, FLST, KYWD

The rest of currently supported form types is as follows: ARMO, GLOB, GMST, IMAD, IMGS, PROJ, WEAP, WTHR

**Comment by unforbidable** [comment]
Took the liberty to make a list in the OP hoping to keep track more easily. (:

**Comment by Desymoo** [comment]
Oh wow! Thank you! I didn't even think to do that, that is such a wonderful idea :) I will include a list in all of the main topics in the future ^^ Great idea.

**Comment by unforbidable** [comment]
Thank you! I figured we could use this issue to track progress with other related XML files so  for now I added the functions.

**Comment by Theamara** [comment]
I could not think of where else to include this, so I will leave it here as a comment :) Here is also the list of unfinished fields that will need their own XML file:

- [ ] virtual-machine (scripting data)
- [ ] body-template (for armor-related records)
- [ ] destructible (destruction data)

**Comment by unforbidable** [comment]
Oh boy, so much to do (: feel free to add it to the op so it adds up to the progress thingy.

**Comment by Desymoo** [comment]
Thank you :D I forgot it wouldn't update the progress bar ^^

**Comment by Desymoo** [comment]
Yay! Finished! :D
