### ISSUE TITLE
Implement new display-name property

### ISSUE THREAD

**Issue by unforbidable** [unforbidable/patcher#53]
As discussed, for various purposes of the GUI side of patcher, some model objects need to be extended to include display name.

Not all model objects need this property, but it seems to make sense for model objects that follow
- [x] RecordModel - Name for the selected forms type
- [x] FieldModel - Labels for controls (covers fields that are field groups and structures)
- [x] MemberModel - Labels for controls
- [x] EnumMemberModel - Lables for values in combo boxes
- [x] FunctionParamModel - Labels when entering function parameters

Just in case this wasn't implemented yet, as discussed:
- [x] Display name will automatically adopt the value of name if not provided

(Note: Included reason to make sure we aren't missing anything)

**Comment by Desymoo** [comment]
Aye, aye captain :D

**Comment by unforbidable** [comment]
Added `FunctionParamModel` as discussed. (:

**Comment by Desymoo** [comment]
Finished adding it to the above mentioned models :) If you could check on the FunctionParamModel to make sure it was added correctly, that would be lovely! I had a bit of trouble and just wanted to make sure it was correct.

And I also wanted to make sure that we had added the ability for display names to take on the value of the name property as well before we closed this issue :) So I added it as a task up above.
