### ISSUE TITLE
Support for long, ulong, bool types for members and as types

### ISSUE THREAD

**Issue by unforbidable** [unforbidable/patcher#57]
Add `long`, `ulong` and `bool` types to be supported by `MemberType` and `TargetType` models.

**Comment by Desymoo** [comment]
Support has been added for these two types :)

**Comment by unforbidable** [comment]
It seems we might need `bool` as well, can you do that too please? (:

**Comment by Desymoo** [comment]
Done! I also added support for `lstring` for `TargetType`, as the game setting form did have one of those as well. Hopefully that wasn't unnecessary :)

**Comment by unforbidable** [comment]
Well, since `TargetType` is information for the GUI, it depends on whether we want the GUI to know a string can be localized, and then if the active plugin supports localization, let the user pick a string from the appropriate string table. So far patcher could only read localized strings not edit and save. So I guess since you added `lstring` now we need to support editing localized strings! (; So, please also add `dlstring` and `ilstring`. (Note that only `StringLocalization` property is needed for the `TargetType` and it needs to be added to the class, i.e. `IsZeroTerminatedString` and `StringPrefixSize` are not needed.) I'll explain in detail later. (:

**Comment by Desymoo** [comment]
Oops, sorry about that ^^ I just noticed that lstring was one of the types in gmst, so I thought I would add it. I've fixed the StringLocalization property and added ilstring and dlstring :) Thank you for the comment! It's very helpful when I need to fix little mistakes like that! ^^
